version: '3.8'
services:

    # Application
    app:
        container_name: app
        build:
          args:
            user: selim
            uid: 1000
          context: .
          dockerfile: ./docker/app.dockerfile
        working_dir: /var/www
        restart: unless-stopped
        volumes:
            - ./:/var/www
        depends_on:
            - db
            - mongodb
    # Web Server
    web:
        container_name: web
        build:
            context: .
            dockerfile: ./docker/web.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "app"
        ports:
            - 80:80
    # Database
    db:
        image: mysql:8.0
        container_name: db
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: ${DB_USERNAME}
        ports:
            - "3306:3306"
        restart: unless-stopped
    # MongoDB
    mongodb:
        container_name: mongodb
        image: mongo
        ports:
            - 27017:27017
        logging:
            driver: none
    # Database management phpmyadmin
    pma:
        image: phpmyadmin:5.1
        container_name: pma
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${DB_HOST}
            - PMA_USER=${DB_USERNAME}
            - PMA_PASSWORD=${DB_PASSWORD}
            - PMA_PORT=${DB_PORT}
        depends_on:
            - db
        ports:
            - 8888:80
    # Mailing Server
    mailhog:
        container_name: mailhog
        image: mailhog/mailhog
        logging:
            driver: 'none'
        ports:
            - 1025:1025
            - 8025:8025

volumes:
    dbdata:
